### PR TITLE
Add proper loading class to Notification loading icon

### LINKED ISSUE #29: Loading icon is not animated
When loading the application, the loading icon is not animated:

Screen Shot 2021-12-13 at 12 52 08 PM

It appears the `cf-icon-svg__updating` class needs to be added to https://github.com/cfpb/rental-assistance-finder/blob/main/src/Notification.js#L7 per the guidance in https://cfpb.github.io/design-system/foundation/iconography#animated-icon-1

### PR DESCRIPTION
**Pull request by wpears**
Closes #29

### CODE REVIEW

**Comment by anselmbradford** [comment]
Is the test failure related to this PR?

**Comment by wpears** [comment]
Nope, seems like some of the failing browser test state match what's live in prod (eg, only 2 results for travis co, texas)

**Comment by virginiacc** [comment]
Yes, unfortunately those tests are going to fail at the moment because they assume (accurately) that each state has its own program, but we are (at least temporarily, while we determine how to show program status in the tool) removing the Texas program in the data processing script since that program is out of funds and no longer accepting applicants. Ideally we would continue to show all programs, noting the ones that are closed, and the tests would pass as is. We could also rewrite the tests to actually check the data for the existence of state level programs. 

I'm not sure that it's strictly necessary to run the two data-checking tests against every PR -- they were written to verify a specific update when we made a substantive change to how data was displayed / filtered by county in the tool -- but I suppose it doesn't hurt to run them generally (except possibly in this instance ;)

**Review by virginiacc — APPROVED** [review]
Looks good -- thanks for making this update!

**Pull request merged**
